config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'points#index'
  
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :users do
    member do
      get 'pointview'
      get 'pointspend'
    end
  end
  
  resources :spends

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
end

app/models/save.rb
class Save < Point
end

app/models/spend.rb
class Spend < Point
end

app/models/user.rb
class User < ActiveRecord::Base
    VALID_NUMBER_REGEX = /\d+/    
    validates :number, presence: true, length: { is: 11 },
                    format: { with: VALID_NUMBER_REGEX },
                    uniqueness: { case_sensitive: false }
                    
    validates :password, presence: true, length: { is: 6 },
                    format: { with: VALID_NUMBER_REGEX },
                    uniqueness: { case_sensitive: false }
                    
    has_secure_password
    
    has_many :saves, class_name: "Save"
    has_many :spends
end


# knives  -> knife
# saves  -> safe

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :set_request_from
  
  def set_request_from
    if session[:request_from]
      @request_from = session[:request_from]
    end
    session[:request_from] = request.original_url
  end
  
  def return_back
    if request.referer
      redirect_to :back
      return true
    elsif @request_from
      redirect_to @request_from
      return true
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(number: params[:session][:number].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.number}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController

def create

   Spend.create(spend_params)
   @user_id = params[:spend][:user_id]
   @user = User.find(@user_id)
   redirect_to @user
end

private

  def spend_params
    params.require(:spend).permit(:user_id, :point)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:index, :show, :edit, :update, :followings, :followers]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録完了しました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def pointview
    @user = User.find(params[:id])
    @saves = @user.saves
    @spends = @user.spends
    @totalpoint = 0
    @saves.each do |s|
         @totalpoint += s.point
    end
    @spends.each do |sp|
         @totalpoint -= sp.point
    end
  end
  
  def pointspend
    @user = User.find(params[:id])
    @spend = @user.spends.build
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Update profile"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

 

  private

  def user_params
    params.require(:user).permit(:number, :password,
                                 :password_confirmation)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def correct_user
    redirect_to root_path if current_user != @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/points/index.html.erb
<h1>Points#index</h1>
<div class="user">
    <h3><%= link_to "新規登録", signup_path %></h3>
    <h3><%= link_to "ご登録済みの方", login_path %></h3>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>番号とパスワードを設定してください</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :電話番号 %>
      <%= f.text_field :number, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード再確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>


      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
    <p><%= link_to "login" , login_path %></p>
  </div>
</div>

app/views/users/pointspend.html.erb
<%= form_for(@spend) do |f| %>

    <%= f.number_field :point %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit "ポイントを使う" %>
    
<% end %>
<p><%= link_to "戻る" , user_path %></p>

app/views/users/pointview.html.erb
<% if @saves.any? %>
  <%#ポイント登録がある時は %>
  Totalpoint: <%= @totalpoint %>
  <br>
  
  point ためた履歴<br>
  <% @saves.each do |f| %>
     <%= f.point %>　point -> <%= f.created_at %> <br>
  <% end %>
  
  point使った履歴<br>
  <% @spends.each do |f| %>
      <%= f.point %> point -> <%= f.created_at %> <br>
  <% end %>
<% end %>
<p><%= link_to "戻る" , user_path %></p>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <p>電話番号</p>
        <%= @user.number %>
    </div>
    
    
        <p><%= link_to "ポイントを見る", pointview_user_path(@user) %></p>
        <p><%= link_to "ポイントを使う", pointspend_user_path(@user) %></p>
        <p><%= link_to "ログアウト", root_path %></p>
</div>